[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "inermodz"
version = "1.0.0"
description = "Compute and display inertial modes of a full sphere using the analytical solution of Zhang et al. (2001)"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{ name = "Ankit Barik" }]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2",
    "matplotlib>=3.8",
    "cartopy",
    "pyvista",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization"
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Repository = "https://github.com/AnkitBarik/inermodz"
